### PR TITLE
Element filtering

### PR DESCRIPTION
**Pull request by willbamford**
Enables optional filtering of the serialised JSON elements. An example use case is when serialising elements with Raphael.FreeTransform applied - you may not want to serialise the FT handles etc. in which case you could check if the element itself had a 'freeTransform' property (in which case allow it to be serialised by returning true from the filter function).

Trivial example:

``` javascript

var paper = Raphael(0, 0, 400, 400);

var circle = paper.circle(50, 50, 50).attr('fill', '#0f0');

var filter = function (el) {
    return el.type === "circle"; // Only allow 'circles' to be serialised
};

paper.toJSON(filter);
```

### CODE REVIEW

**Comment by AliasIO** [comment]
You made me think of something better. How about adding a callback that lets you add and remove methods, or skip the element completely.

``` javascript
paper.toJSON(function(el, data) {
    // Only serialize elements of type circle
    if ( el.type !== 'circle' ) return false;

    // Do something with element before serialization
    if ( el.freeTransform ) paper.freeTransform(el).unplug();

    // Add a custom method to serialized data
    data.customMethod = el.customMethod;

    return data;
});

```

**Comment by willbamford** [comment]
Great idea. Might also be worth considering a similar callback for fromJSON to allow you to reinitialise state on an element-by-element basis.

BTW - would you consider also implementing a callback option for Raphael.Export as it would be great to allow filtering here too?

**Comment by AliasIO** [comment]
I agree `fromJSON` should have a similar callback. Not sure how useful it would be in Raphael.Export.

**Comment by AliasIO** [comment]
A slightly different implementation but I think this works well. 27feebc62a3a05835c9f6f6db9837d24b7052a01

**Pull request closed without merging**
